export default [{'name': 'job family', 'char': 'ACADEMY TRAINER'},
{'name': 'job family', 'char': 'ACCOUNTANT'},
{'name': 'job family', 'char': 'ACCOUNTING'},
{'name': 'job family', 'char': 'ACQUISITION'},
{'name': 'job family', 'char': 'ACQUISITIONS'},
{'name': 'job family', 'char': 'ADMINISTRATIVE ASSISTANT'},
{'name': 'job family', 'char': 'ADMINISTRATIVE_SUPPORT'},
{'name': 'job family', 'char': 'ADVANCED ANALYTICS'},
{'name': 'job family', 'char': 'ADVERTISING'},
{'name': 'job family', 'char': 'ANALYST'},
{'name': 'job family', 'char': 'ANALYTICS'},
{'name': 'job family', 'char': 'ANALYTICS\xa0 OPTIMIZATION'},
{'name': 'job family', 'char': 'ANALYTICS & OPTIMIZATION'},
{'name': 'job family', 'char': 'AREA-MANAGER'},
{'name': 'job family', 'char': 'ASSEMBLY'},
{'name': 'job family', 'char': 'ASSET PROTECTION'},
{'name': 'job family', 'char': 'ASSET_AND_PROPERTY_MANAGEMENT'},
{'name': 'job family', 'char': 'ASSET_PROTECTION'},
{'name': 'job family', 'char': 'ASSOCIATE REWARDS'},
{'name': 'job family', 'char': 'ASSOCIATE_AND_LABOR_RELATIONS'},
{'name': 'job family', 'char': 'ASSOCIATE_REWARDS'},
{'name': 'job family', 'char': 'ASST-GENERAL-MANAGER'},
{'name': 'job family', 'char': 'ASST-GENERAL-MANAGER-TRANS'},
{'name': 'job family', 'char': 'AUDIT'},
{'name': 'job family', 'char': 'AUDITOR'},
{'name': 'job family', 'char': 'AVIATION'},
{'name': 'job family', 'char': 'BACKROOM ASSOCIATE'},
{'name': 'job family', 'char': 'BAKERY I'},
{'name': 'job family', 'char': 'BAKERY II'},
{'name': 'job family', 'char': 'BAKERY LEAD'},
{'name': 'job family', 'char': 'BILLING_AND_COLLECTIONS'},
{'name': 'job family', 'char': 'BRAND_MANAGEMENT'},
{'name': 'job family', 'char': 'BUILD\xa0 PRODUCTION'},
{'name': 'job family', 'char': 'BUILD & PRODUCTION'},
{'name': 'job family', 'char': 'BUSINESS_ANALYSIS_AND_INSIGHTS'},
{'name': 'job family', 'char': 'BUSINESS_DEVELOPMENT'},
{'name': 'job family', 'char': 'BUSINESS_LEAD'},
{'name': 'job family', 'char': 'BUSINESS_OPERATIONS'},
{'name': 'job family', 'char': 'BUYER'},
{'name': 'job family', 'char': 'CAFETERIA'},
{'name': 'job family', 'char': 'CATEGORY MANAGEMENT'},
{'name': 'job family', 'char': 'CHANGE_MANAGEMENT'},
{'name': 'job family', 'char': 'CIVIL'},
{'name': 'job family', 'char': 'CLAIMS'},
{'name': 'job family', 'char': 'CLERICAL'},
{'name': 'job family', 'char': 'CLINICAL_OPERATIONS'},
{'name': 'job family', 'char': 'COMMUNICATIONS'},
{'name': 'job family', 'char': 'COMPLIANCE_AND_ETHICS_GENERALIST'},
{'name': 'job family', 'char': 'CONNECTION'},
{'name': 'job family', 'char': 'CONSTRUCTION_MANAGEMENT'},
{'name': 'job family', 'char': 'CONSULTANT'},
{'name': 'job family', 'char': 'CONTRACT_MANAGEMENT'},
{'name': 'job family', 'char': 'COORDINATOR'},
{'name': 'job family', 'char': 'CORPORATE AFFAIRS'},
{'name': 'job family', 'char': 'CORPORATE SECURITY'},
{'name': 'job family', 'char': 'CORPORATE_LAW'},
{'name': 'job family', 'char': 'CREATIVE_AND_DESIGN'},
{'name': 'job family', 'char': 'CUSTOMER\xa0 MGMT TEAM'},
{'name': 'job family', 'char': 'CUSTOMER - MGMT. TEAM'},
{'name': 'job family', 'char': 'CUSTOMER_SERVICE'},
{'name': 'job family', 'char': 'CYBER_SECURITY'},
{'name': 'job family', 'char': 'DATA'},
{'name': 'job family', 'char': 'DATA SCIENCE'},
{'name': 'job family', 'char': 'DATA SCIENTIST'},
{'name': 'job family', 'char': 'DATA_ANALYTICS'},
{'name': 'job family', 'char': 'DATA_ANALYTICS_AND_MANAGEMENT'},
{'name': 'job family', 'char': 'DATA_MANAGEMENT'},
{'name': 'job family', 'char': 'DATA_SCIENCE'},
{'name': 'job family', 'char': 'DESIGN'},
{'name': 'job family', 'char': 'DESIGNER'},
{'name': 'job family', 'char': 'DIGITAL_MARKETING'},
{'name': 'job family', 'char': 'DIRECTOR'},
{'name': 'job family', 'char': 'DIVISIONAL MANAGER - AP'},
{'name': 'job family', 'char': 'DIVISIONAL MANAGER - FINANCE'},
{'name': 'job family', 'char': 'DIVISIONAL MANAGER - H&W'},
{'name': 'job family', 'char': 'DIVISIONAL MANAGER - HR'},
{'name': 'job family', 'char': 'DIVISIONAL MANAGER - MERCH'},
{'name': 'job family', 'char': 'ELECTRICAL'},
{'name': 'job family', 'char': 'EMERGENCY_MANAGEMENT'},
{'name': 'job family', 'char': 'ENGINEER'},
{'name': 'job family', 'char': 'ENGINEERING'},
{'name': 'job family', 'char': 'EVENT_PLANNING'},
{'name': 'job family', 'char': 'EVP'},
{'name': 'job family', 'char': 'EXECUTIVE'},
{'name': 'job family', 'char': 'EXECUTIVE ASSISTANT'},
{'name': 'job family', 'char': 'EXPAT'},
{'name': 'job family', 'char': 'EXPERIENCE\xa0 INNOVATION'},
{'name': 'job family', 'char': 'EXPERIENCE & INNOVATION'},
{'name': 'job family', 'char': 'FACILITATOR'},
{'name': 'job family', 'char': 'FACILITIES MAINTENANCE'},
{'name': 'job family', 'char': 'FACILITIES_MAINTENANCE'},
{'name': 'job family', 'char': 'FACILITY_DESIGN'},
{'name': 'job family', 'char': 'FINANCE\xa0 MGMT TEAM'},
{'name': 'job family', 'char': 'FINANCE - MGMT. TEAM'},
{'name': 'job family', 'char': 'FINANCE SERVICES'},
{'name': 'job family', 'char': 'FINANCIAL_ANALYSIS'},
{'name': 'job family', 'char': 'FOOD_SERVICE'},
{'name': 'job family', 'char': 'FP&A'},
{'name': 'job family', 'char': 'FPA'},
{'name': 'job family', 'char': 'FREEZER/COOLER/DELI\xa0'},
{'name': 'job family', 'char': 'FUEL/CAR WASH'},
{'name': 'job family', 'char': 'GENERAL MANAGER'},
{'name': 'job family', 'char': 'GENERAL MANAGER-DEV(LOGS)'},
{'name': 'job family', 'char': 'GENERAL MANAGER-TRANS'},
{'name': 'job family', 'char': 'GIVING'},
{'name': 'job family', 'char': 'GROUND_TRANSPORTATION'},
{'name': 'job family', 'char': 'GUIDE'},
{'name': 'job family', 'char': 'H&W-ASSISTANT MANAGER'},
{'name': 'job family', 'char': 'H&W-CERT VISION CENTER MANAGER'},
{'name': 'job family', 'char': 'H&W-CERT/LIC TECH'},
{'name': 'job family', 'char': 'H&W-CERTIFIED OPTICIAN'},
{'name': 'job family', 'char': 'H&W-DR. OF OPTOMETRY'},
{'name': 'job family', 'char': 'H&W-GRAD INTERN'},
{'name': 'job family', 'char': 'H&W-LIC OPTICIAN'},
{'name': 'job family', 'char': 'H&W-LIC VISION CENTER MANAGER'},
{'name': 'job family', 'char': 'H&W-LICENSED OPTICIAN'},
{'name': 'job family', 'char': 'H&W-MEDICAL ASSISTANT'},
{'name': 'job family', 'char': 'H&W-NON CRED OPTICAL ASSOCIATE'},
{'name': 'job family', 'char': 'H&W-NON CRED PHARMACY ASSOCIATE'},
{'name': 'job family', 'char': 'H&W-NON STORE OPERATIONS'},
{'name': 'job family', 'char': 'H&W-NURSE PRACTITIONER'},
{'name': 'job family', 'char': 'H&W-OPTICAL MANAGER'},
{'name': 'job family', 'char': 'H&W-OPTICIAN'},
{'name': 'job family', 'char': 'H&W-OPTOMETRY INTERN'},
{'name': 'job family', 'char': 'H&W-PHARM CLINICAL SERVICES MANAGER'},
{'name': 'job family', 'char': 'H&W-PHARM MANAGER'},
{'name': 'job family', 'char': 'H&W-PHARM TECH'},
{'name': 'job family', 'char': 'H&W-PHARMACIST'},
{'name': 'job family', 'char': 'H&W-PHARMACY AREA MANAGER'},
{'name': 'job family', 'char': 'H&W-PHARMACY MANAGER'},
{'name': 'job family', 'char': 'H&W-PHARMACY-PHARMACY-INTERN'},
{'name': 'job family', 'char': 'H&W-PRE-GRAD'},
{'name': 'job family', 'char': 'H&W-VISION CENTER ASSOCIATE'},
{'name': 'job family', 'char': 'H&W-VISION CENTER MANAGER'},
{'name': 'job family', 'char': 'HEALTHCARE'},
{'name': 'job family', 'char': 'HR_EXPERTS'},
{'name': 'job family', 'char': 'HR_GENERALIST'},
{'name': 'job family', 'char': 'INDUSTRIAL'},
{'name': 'job family', 'char': 'INFRASTRUCTURE'},
{'name': 'job family', 'char': 'INITIATIVES_AND_OFFERINGS'},
{'name': 'job family', 'char': 'INSTRUCTOR'},
{'name': 'job family', 'char': 'INTERN'},
{'name': 'job family', 'char': 'INVENTORY_MANAGEMENT'},
{'name': 'job family', 'char': 'INVESTIGATIONS'},
{'name': 'job family', 'char': 'INVESTIGATOR'},
{'name': 'job family', 'char': 'JANITORIAL'},
{'name': 'job family', 'char': 'JET'},
{'name': 'job family', 'char': 'JET PRIVATE LABEL'},
{'name': 'job family', 'char': 'JETFRESH'},
{'name': 'job family', 'char': 'JEWELLERY'},
{'name': 'job family', 'char': 'LEAD'},
{'name': 'job family', 'char': 'LEARNING_AND_DEVELOPMENT'},
{'name': 'job family', 'char': 'LEGAL'},
{'name': 'job family', 'char': 'LEGAL COUNSEL'},
{'name': 'job family', 'char': 'LEGAL SERVICES'},
{'name': 'job family', 'char': 'LIFT DRIVER'},
{'name': 'job family', 'char': 'LIQUOR CASHIER'},
{'name': 'job family', 'char': 'LIQUOR CLERK (4754 ONLY)'},
{'name': 'job family', 'char': 'LIQUOR LEAD (4754 ONLY)'},
{'name': 'job family', 'char': 'MAINTENANCE'},
{'name': 'job family', 'char': 'MAINTENANCE/SERVICE SHOP'},
{'name': 'job family', 'char': 'MANAGER'},
{'name': 'job family', 'char': 'MARKETING'},
{'name': 'job family', 'char': 'MEAT I'},
{'name': 'job family', 'char': 'MEAT II'},
{'name': 'job family', 'char': 'MEAT LEAD'},
{'name': 'job family', 'char': 'MECHANICAL'},
{'name': 'job family', 'char': 'MEMBER ASSIST'},
{'name': 'job family', 'char': 'MEMBER FRONTLINE'},
{'name': 'job family', 'char': 'MEMBER SERVICES\xa0 TECHNICAL OPS'},
{'name': 'job family', 'char': 'MEMBER SERVICES & TECHNICAL OPS'},
{'name': 'job family', 'char': 'MEMBER SERVICES LEAD'},
{'name': 'job family', 'char': 'MEMBER SUPPORT'},
{'name': 'job family', 'char': 'MEMBERSHIP COORDINATOR'},
{'name': 'job family', 'char': 'MEMBERSHIP LEAD'},
{'name': 'job family', 'char': 'MERCHANDISING'},
{'name': 'job family', 'char': 'MERCHANDISING LEAD'},
{'name': 'job family', 'char': 'MERCHANT'},
{'name': 'job family', 'char': 'MGMT-ACADEMY FACILITATOR'},
{'name': 'job family', 'char': 'MGMT-ACADEMY MANAGER'},
{'name': 'job family', 'char': 'MGMT-ACCM'},
{'name': 'job family', 'char': 'MGMT-ASSET PROTECTION MANAGER'},
{'name': 'job family', 'char': 'MGMT-ASSISTANT MANAGER'},
{'name': 'job family', 'char': 'MGMT-CLUB MANAGER'},
{'name': 'job family', 'char': 'MGMT-CO-MANAGER'},
{'name': 'job family', 'char': 'MGMT-DEV CLUB MGR'},
{'name': 'job family', 'char': 'MGMT-DEVELOPMENTAL CO-MANAGER'},
{'name': 'job family', 'char': 'MGMT-DEVELOPMENTAL STORE MANAGER'},
{'name': 'job family', 'char': 'MGMT-DIVISIONAL MANAGER'},
{'name': 'job family', 'char': 'MGMT-EMERGING STORE MANAGER'},
{'name': 'job family', 'char': 'MGMT-FUEL STATION MANAGER'},
{'name': 'job family', 'char': 'MGMT-HR MANAGER'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGEMER - OGP'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - AP'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - APM'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - DEVELOPMENTAL'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - FRESH'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - H&W'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - HR'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - OPTICAL'},
{'name': 'job family', 'char': 'MGMT-MARKET MANAGER - RETAIL'},
{'name': 'job family', 'char': 'MGMT-MERCH/OPS'},
{'name': 'job family', 'char': 'MGMT-MIT'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - AP'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - CMI'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - COMPLIANCE'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - FINANCE'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - FRESH'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - GS'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - H&W'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - HR'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - LOGISTICS'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - MERCH'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - OGP'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - REALTY'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - REL'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER - TRAVEL'},
{'name': 'job family', 'char': 'MGMT-REGIONAL MANAGER-H&W'},
{'name': 'job family', 'char': 'MGMT-STORE MANAGER'},
{'name': 'job family', 'char': 'MGMT-TRAINING FACILITATOR'},
{'name': 'job family', 'char': 'MGMT-UNCLASSIFIED'},
{'name': 'job family', 'char': 'NETWORK_ENGINEERING'},
{'name': 'job family', 'char': 'NON-MGMT-ACADEMY'},
{'name': 'job family', 'char': 'NON-MGMT-ACCOUNTING/PERSONNEL'},
{'name': 'job family', 'char': 'NON-MGMT-AP'},
{'name': 'job family', 'char': 'NON-MGMT-ASSEMBLER'},
{'name': 'job family', 'char': 'NON-MGMT-ASSET PROTECTION ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-ASSET PROTECTION MANAGER'},
{'name': 'job family', 'char': 'NON-MGMT-ASSET PROTECTION TRAINEE'},
{'name': 'job family', 'char': 'NON-MGMT-BAKERY ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-CASHIER'},
{'name': 'job family', 'char': 'NON-MGMT-CLAIMS/DSD ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-COURTESY ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-CUSTOMER SERVICE SUPERVISOR'},
{'name': 'job family', 'char': 'NON-MGMT-DEMO\xa0'},
{'name': 'job family', 'char': 'NON-MGMT-FRESH ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-FRESH-CAFEE'},
{'name': 'job family', 'char': 'NON-MGMT-FRESH-DELI/MEAT'},
{'name': 'job family', 'char': 'NON-MGMT-FRESH-FLORAL'},
{'name': 'job family', 'char': 'NON-MGMT-FRONT END ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-FUEL ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-HOURLY SUPERVISOR'},
{'name': 'job family', 'char': 'NON-MGMT-INTERN'},
{'name': 'job family', 'char': 'NON-MGMT-MAINTENANCE'},
{'name': 'job family', 'char': 'NON-MGMT-MEMBER SERVICE ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-MEMBERSHIP/MARKETING'},
{'name': 'job family', 'char': 'NON-MGMT-MERCH/OPS'},
{'name': 'job family', 'char': 'NON-MGMT-MRA'},
{'name': 'job family', 'char': 'NON-MGMT-OFFICE ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-OPTOMETRIST'},
{'name': 'job family', 'char': 'NON-MGMT-ORDER FULFILLMENT'},
{'name': 'job family', 'char': 'NON-MGMT-OTHER'},
{'name': 'job family', 'char': 'NON-MGMT-PEOPLE GREETER'},
{'name': 'job family', 'char': 'NON-MGMT-PERSONAL SHOPPER'},
{'name': 'job family', 'char': 'NON-MGMT-PTC'},
{'name': 'job family', 'char': 'NON-MGMT-RECEIVING'},
{'name': 'job family', 'char': 'NON-MGMT-SALES ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-STOCKER'},
{'name': 'job family', 'char': 'NON-MGMT-SUPPORT MANAGER'},
{'name': 'job family', 'char': 'NON-MGMT-TLE ASSOCIATE'},
{'name': 'job family', 'char': 'NON-MGMT-ZONE MERCHANDISE SUPERVISOR'},
{'name': 'job family', 'char': 'OFFICE FIXED'},
{'name': 'job family', 'char': 'OPERATIONS_ANALYST'},
{'name': 'job family', 'char': 'OPERATIONS_MANAGEMENT'},
{'name': 'job family', 'char': 'OPERATIONS_MANAGER'},
{'name': 'job family', 'char': 'OPERATIONS-MANAGER'},
{'name': 'job family', 'char': 'OPERATOR'},
{'name': 'job family', 'char': 'OPTICAL'},
{'name': 'job family', 'char': 'OPTICAL_CARE'},
{'name': 'job family', 'char': 'OPTICIAN'},
{'name': 'job family', 'char': 'OPTICIAN DUAL CERT'},
{'name': 'job family', 'char': 'Optician Dual Cert\xa0'},
{'name': 'job family', 'char': 'OPTICIAN SINGLE & DUAL LICENSE'},
{'name': 'job family', 'char': 'Optician Single & Dual License\xa0'},
{'name': 'job family', 'char': 'OPTICIAN SINGLE LICENSE'},
{'name': 'job family', 'char': 'ORDERFILLING'},
{'name': 'job family', 'char': 'OTHER'},
{'name': 'job family', 'char': 'PACKAGING'},
{'name': 'job family', 'char': 'PARALEGAL'},
{'name': 'job family', 'char': 'PARTNERSHIP MARKETING'},
{'name': 'job family', 'char': 'PARTNERSHIPS'},
{'name': 'job family', 'char': 'PAYROLL'},
{'name': 'job family', 'char': 'PEOPLE LEAD'},
{'name': 'job family', 'char': 'PHARMACIST'},
{'name': 'job family', 'char': 'PHARMACY'},
{'name': 'job family', 'char': 'PHARMACY TECH'},
{'name': 'job family', 'char': 'PHARMACY TECH CERTIFIED'},
{'name': 'job family', 'char': 'PILOT'},
{'name': 'job family', 'char': 'PLANNER'},
{'name': 'job family', 'char': 'PLANNING'},
{'name': 'job family', 'char': 'PLANT_MANAGEMENT'},
{'name': 'job family', 'char': 'PMDC'},
{'name': 'job family', 'char': 'PMO'},
{'name': 'job family', 'char': 'PREPARED FOOD I'},
{'name': 'job family', 'char': 'PREPARED FOOD II'},
{'name': 'job family', 'char': 'PREPARED FOOD LEAD'},
{'name': 'job family', 'char': 'Prepared Food\xa0\xa0 I'},
{'name': 'job family', 'char': 'Prepared Food\xa0\xa0 II'},
{'name': 'job family', 'char': 'PRICING'},
{'name': 'job family', 'char': 'PROCESS_IMPROVEMENT'},
{'name': 'job family', 'char': 'PROCUREMENT'},
{'name': 'job family', 'char': 'PRODUCE I'},
{'name': 'job family', 'char': 'PRODUCE LEAD'},
{'name': 'job family', 'char': 'PRODUCT MANAGEMENT'},
{'name': 'job family', 'char': 'PRODUCT_DEVELOPMENT'},
{'name': 'job family', 'char': 'PRODUCT_MANAGEMENT'},
{'name': 'job family', 'char': 'PROGRAM MANAGEMENT'},
{'name': 'job family', 'char': 'PROGRAM_MANAGEMENT'},
{'name': 'job family', 'char': 'PROJECT_MANAGEMENT'},
{'name': 'job family', 'char': 'PUBLIC_AFFAIRS'},
{'name': 'job family', 'char': 'PUBLIC_RELATIONS'},
{'name': 'job family', 'char': 'PURCHASING'},
{'name': 'job family', 'char': 'QA'},
{'name': 'job family', 'char': 'QUALITY'},
{'name': 'job family', 'char': 'QUALITY CONTROL'},
{'name': 'job family', 'char': 'QUALITY_ENGINEERING'},
{'name': 'job family', 'char': 'RECEIVING'},
{'name': 'job family', 'char': 'RESEARCH_AND_INNOVATION'},
{'name': 'job family', 'char': 'RETAIL\xa0 MGMT TEAM\xa0 RETAIL PRODUCT'},
{'name': 'job family', 'char': 'RETAIL\xa0 MGMT TEAMRETAIL PRODUCT'},
{'name': 'job family', 'char': 'RETAIL ANALYTICS'},
{'name': 'job family', 'char': 'RETAIL CORE ENGINE'},
{'name': 'job family', 'char': 'RETAIL PRODUCT'},
{'name': 'job family', 'char': 'RETURN CENTER'},
{'name': 'job family', 'char': 'RISK_MANAGEMENT'},
{'name': 'job family', 'char': 'SEASONAL'},
{'name': 'job family', 'char': 'SECURITY'},
{'name': 'job family', 'char': 'SERVICES_SUPPORT'},
{'name': 'job family', 'char': 'SHIPPING'},
{'name': 'job family', 'char': 'SITE MERCHANDISING'},
{'name': 'job family', 'char': 'SOFTWARE ENGINEER'},
{'name': 'job family', 'char': 'SOFTWARE_ENGINEERING_AND_ARCHITECTUR'},
{'name': 'job family', 'char': 'SOURCING'},
{'name': 'job family', 'char': 'SPECIALIST'},
{'name': 'job family', 'char': 'SPECIALTY_COMPLIANCE_AND_ETHICS'},
{'name': 'job family', 'char': 'SR DIRECTOR'},
{'name': 'job family', 'char': 'SR MANAGER'},
{'name': 'job family', 'char': 'SR MANGER'},
{'name': 'job family', 'char': 'STAR'},
{'name': 'job family', 'char': 'STORE 8'},
{'name': 'job family', 'char': 'STRATEGIC INITIATIVES'},
{'name': 'job family', 'char': 'STRATEGY AND BUSINESS DEVELOPMENT'},
{'name': 'job family', 'char': 'SUPERVISOR'},
{'name': 'job family', 'char': 'SUPPLY CHAIN\xa0 FULFILLMENT'},
{'name': 'job family', 'char': 'SUPPLY CHAIN & FULFILLMENT'},
{'name': 'job family', 'char': 'SUPPLY_CHAIN_MANAGEMENT'},
{'name': 'job family', 'char': 'SUPPORT'},
{'name': 'job family', 'char': 'SUPPORT_SERVICES'},
{'name': 'job family', 'char': 'SUSTAINABILITY'},
{'name': 'job family', 'char': 'SVP'},
{'name': 'job family', 'char': 'SYSTEM ADMINISTRATOR'},
{'name': 'job family', 'char': 'SYSTEMS_ENGINEERING'},
{'name': 'job family', 'char': 'TALENT ACQUISITION'},
{'name': 'job family', 'char': 'TALENT BUSINESS PARTNERS'},
{'name': 'job family', 'char': 'TALENT DEVELOPMENT'},
{'name': 'job family', 'char': 'TALENT EXPERIENCE'},
{'name': 'job family', 'char': 'TALENT OPERATIONS'},
{'name': 'job family', 'char': 'TAX'},
{'name': 'job family', 'char': 'TBC LEAD'},
{'name': 'job family', 'char': 'TBC TIRE TECH'},
{'name': 'job family', 'char': 'TEAM ASSOCIATE'},
{'name': 'job family', 'char': 'TEAM LEAD'},
{'name': 'job family', 'char': 'TECHNICAL'},
{'name': 'job family', 'char': 'TECHNICAL_PROGRAM_MANAGEMENT'},
{'name': 'job family', 'char': 'TECHNICIAN'},
{'name': 'job family', 'char': 'TECHNOLOGIST'},
{'name': 'job family', 'char': 'TECHNOLOGY'},
{'name': 'job family', 'char': 'TECHNOLOGY OPERATIONS'},
{'name': 'job family', 'char': 'TECHNOLOGY_SUPPORT'},
{'name': 'job family', 'char': 'TEMP'},
{'name': 'job family', 'char': 'TRAINEE'},
{'name': 'job family', 'char': 'TRAINER'},
{'name': 'job family', 'char': 'TRANSPORTATION'},
{'name': 'job family', 'char': 'TRANSPORTATION_MAINTENANCE'},
{'name': 'job family', 'char': 'TRANSPORTATION_MANAGEMENT'},
{'name': 'job family', 'char': 'TREASURY'},
{'name': 'job family', 'char': 'TRUCK DRIVER'},
{'name': 'job family', 'char': 'VP'},
{'name': 'job family', 'char': 'WAREHOUSE_MANAGEMENT'},
{'name': 'job family', 'char': 'WHOLESALE TRADING'},
{'name': 'job family', 'char': 'WHOLESALE TRADING LEAD'},
{'name': 'job family', 'char': 'YARD DRIVER'}];