export default ['headcount for region', 
 'headcount for division',
 'headcount for market',
 'headcount for store',
 'hc for region', 
 'hc for division',
 'hc for market',
 'hc for store',
 'exits for region', 
 'exits for division',
 'exits for market',
 'exits for store',
 'turnover for region', 
 'turnover for division',
 'turnover for market',
 'turnover for store',
 'headcount for job family', 
 'hc for job family', 
 'exits for job family',
 'turnover for job family',
];